spring:
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            # You can use gemini-1.5-flash, gemini-2.0-flash, or gemini-2.5-pro
            model: gemini-2.5-flash
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://3.108.194.133.nip.io:8080/login/oauth2/code/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            redirect-uri: http://3.108.194.133.nip.io:8080/login/oauth2/code/github
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
jwt:
  secret: ${JWT_SECRET}

app:
  appUrl: https://project-9v8d6.vercel.app/
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
server:
  port: 8080