spring:
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            # You can use gemini-1.5-flash, gemini-2.0-flash, or gemini-2.5-pro
            model: gemini-2.5-flash
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
jwt:
  secret: ${JWT_SECRET}

app:
  appUrl: http://localhost:3000
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8080